(deftheme cpp-entwickler.de
  "Created 2019-04-28. Colors are taken from https://www.materialui.co/colors.")

(custom-theme-set-faces
 'cpp-entwickler.de
 '(cursor ((t (:background "#FAFAFA"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#8D6E63"))))
 '(minibuffer-prompt ((t (:weight bold :height 1.2))))
 '(highlight ((t (:background "#757575" :distant-foreground "black"))))
 '(region ((t (:background "#3F51B5" :distant-foreground "white smoke"))))
 '(shadow ((t (:foreground "#757575"))))
 '(secondary-selection ((t (:background "#2196F3" :inherit region))))
 '(trailing-whitespace ((t (:background "#F9A825"))))
 '(font-lock-builtin-face ((t (:foreground "turquoise1" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit shadow))))
 '(font-lock-comment-face ((t (:foreground "#F06292" :inverse-video t :slant italic :weight bold))))
 '(font-lock-constant-face ((t (:foreground "#FF8A65"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face ((t (:foreground "#42A5F5" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#AB47BC" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#FFA726" :weight ultra-bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#8D6E63" :slant oblique :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit font-lock-negation-char-face))))
 '(font-lock-regexp-grouping-construct ((t (:inherit font-lock-negation-char-face))))
 '(font-lock-string-face ((t (:foreground "#FFF9C4"))))
 '(font-lock-type-face ((t (:foreground "#7986CB"))))
 '(font-lock-variable-name-face ((t (:foreground "#81C784"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit link :box (:line-width 1 :color "grey75" :style released-button)))))
 '(link ((t (:underline t :weight bold))))
 '(link-visited ((t (:inherit link :weight light))))
 '(fringe ((t (:background "gray5"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:inherit default))))
 '(mode-line ((t (:weight normal :background "#212121" :inherit default))))
 '(mode-line-buffer-id ((t (:inherit mode-line :weight bold))))
 '(mode-line-emphasis ((t (:inherit mode-line :weight bold))))
 '(mode-line-highlight ((t (:inherit mode-line))))
 '(mode-line-inactive ((t (:inherit mode-line :weight light))))
 '(isearch ((t (:background "#3F51B5"))))
 '(isearch-fail ((t (:background "#f44336"))))
 '(lazy-highlight ((t (:background "#9FA8DA"))))
 '(match ((t (:background "#3F51B5"))))
 '(next-error ((t (:inherit match))))
 '(query-replace ((t (:inherit match))))
 '(powerline-active1 ((t (:background "#9E9E9E" :inherit mode-line))))
 '(powerline-active2 ((t (:background "#3F51B5" :inherit mode-line))))
 '(powerline-inactive1 ((t (:inherit mode-line-inactive :background "gray20"))))
 '(powerline-inactive2 ((t (:inherit mode-line-inactive :background "gray30"))))
 '(helm-source-header ((t (:family "Sans Serif" :height 1.2 :weight bold :foreground "#FAFAFA" :inherit mode-line))))
 '(helm-ff-symlink ((t (:foreground "peach puff"))))
 '(helm-ff-directory ((t (:inherit helm-ff-file :height 1.2 :slant italic :weight ultra-bold))))
 '(helm-ff-invalid-symlink ((t (:foreground "red"))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-executable ((t (:foreground "#8BC34A"))))
 '(helm-ff-dirs ((t (:inherit (font-lock-function-name-face)))))
 '(helm-match ((t (:inverse-video t))))
 '(helm-separator ((t nil)))
 '(helm-selection ((t (:background "#3F51B5" :distant-foreground "#FAFAFA"))))
 '(helm-selection-line ((t (:inherit (highlight)))))
 '(org-block-begin-line ((t (:height 0.7 :foreground "gray50" :background "gray20"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-block ((t (:background "gray20"))))
 '(flycheck-error-list-warning ((t (:foreground "#FF9800" :inherit warning))))
 '(flycheck-error-list-info ((t (:foreground "#3F51B5" :inherit flycheck-error-list-error))))
 '(flycheck-error-list-error ((t (:inherit error))))
 '(flycheck-error-list-checker-name ((t (:inherit shadow))))
 '(flycheck-error-list-line-number ((t (:inherit shadow))))
 '(flycheck-error-list-highlight ((t (:inherit (highlight)))))
 '(flycheck-error-list-column-number ((t (:inherit shadow))))
 '(flycheck-error-list-id ((t (:inherit (font-lock-type-face)))))
 '(flycheck-error ((t (:inherit error :inverse-video t :background "#FAFAFA"))))
 '(flycheck-warning ((t (:inverse-video t :background "#FAFAFA" :inherit warning))))
 '(flycheck-info ((t (:inherit info :background "#FAFAFA" :inverse-video t))))
 '(error ((t (:foreground "#f44336" :weight bold))))
 '(warning ((t (:foreground "#FF9800" :weight bold))))
 '(vhl/default-face ((t (:inherit default :inverse-video t))))
 '(helm-buffer-file ((t (:inherit helm-ff-file))))
 '(helm-grep-match ((t (:inherit match))))
 '(helm-buffer-saved-out ((t (:inherit helm-buffer-file :underline (:color "red" :style wave)))))
 '(helm-buffer-directory ((t (:inherit helm-ff-directory))))
 '(helm-buffer-not-saved ((t (:inherit warning))))
 '(helm-buffer-process ((t (:inherit shadow))))
 '(helm-buffer-size ((t (:inherit shadow))))
 '(helm-helper ((t (:inherit (helm-header)))))
 '(hl-line ((t (:inherit highlight))))
 '(info ((t (:inherit warning :foreground "#8BC34A"))))
 '(hl-todo-info ((t (:inherit info :inverse-video t :weight ultra-bold :height 1.3))))
 '(hl-todo-warning ((t (:inherit warning :inverse-video t :weight ultra-bold :height 1.3))))
 '(hl-todo-error ((t (:inherit error :inverse-video t :weight ultra-bold :height 1.3))))
 '(outline-1 ((t (:inherit default :weight ultra-bold :height 1.4))))
 '(outline-2 ((t (:inherit default :weight ultra-bold :height 1.3))))
 '(outline-3 ((t (:height 1.2 :weight ultra-bold :inherit default))))
 '(outline-4 ((t (:height 1.1 :weight bold :inherit default))))
 '(outline-5 ((t (:weight bold :inherit default :height 1.2))))
 '(outline-6 ((t (:weight bold :inherit default :height 1.2))))
 '(outline-7 ((t (:weight bold :inherit default :height 1.1))))
 '(outline-8 ((t (:weight bold :inherit default :height 1.1))))
 '(org-agenda-done ((t (:foreground "#8BC34A" :strike-through t :weight ultra-bold))))
 '(org-agenda-date ((t (:inherit helm-source-header))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date))))
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date :weight light))))
 '(org-headline-done ((t (:strike-through t :inherit shadow))))
 '(org-agenda-structure ((t (:inherit org-agenda-date))))
 '(company-preview ((t (:foreground "gray60"))))
 '(company-preview-common ((t (:inherit company-preview :weight bold))))
 '(company-tooltip ((t (:background "gray20" :foreground "white smoke"))))
 '(company-tooltip-common ((t (:inherit (company-preview-common company-tooltip)))))
 '(company-tooltip-selection ((t (:inherit helm-selection))))
 '(company-tooltip-common-selection ((t (:inherit (company-tooltip-common company-tooltip-selection)))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip))))
 '(company-scrollbar-fg ((t (:background "white smoke"))))
 '(ediff-even-diff-Ancestor ((t (:inherit ediff-odd-diff-Ancestor))))
 '(ediff-odd-diff-A ((t (:background "coral1" :distant-foreground "white smoke"))))
 '(ediff-fine-diff-Ancestor ((t (:background "RoyalBlue3"))))
 '(ediff-odd-diff-B ((t (:background "DarkSeaGreen1" :distant-foreground "black"))))
 '(ediff-odd-diff-C ((((type pc)) (:background "gray40" :foreground "yellow3")) (((class color) (min-colors 88)) (:background "Grey")) (((class color) (min-colors 16)) (:background "Grey" :foreground "White")) (((class color)) (:weight bold :background "black" :foreground "yellow3")) (t (:stipple "gray1" :italic t))))
 '(ediff-odd-diff-Ancestor ((t (:background "LightSkyBlue1" :distant-foreground "white smoke"))))
 '(ediff-current-diff-Ancestor ((t (:background "SteelBlue1" :weight bold :inherit ediff-odd-diff-Ancestor))))
 '(ediff-fine-diff-A ((t (:inherit ediff-current-diff-A :background "firebrick1"))))
 '(ediff-fine-diff-B ((t (:inherit ediff-current-diff-B :background "forest green"))))
 '(ediff-fine-diff-C ((t (:inherit ediff-current-diff-C :background "#aaaa22"))))
 '(ediff-current-diff-A ((t (:inherit ediff-odd-diff-A :background "tomato3" :weight bold))))
 '(ediff-current-diff-B ((t (:inherit ediff-odd-diff-B :background "SeaGreen1" :weight bold))))
 '(ediff-current-diff-C ((((class color) (min-colors 88) (background light)) (:background "#ffffaa")) (((class color) (min-colors 88) (background dark)) (:background "#888833")) (((class color) (min-colors 16)) (:background "Pink" :foreground "Navy")) (((class color)) (:weight bold :background "yellow3" :foreground "cyan3")) (t (:inverse-video t))))
 '(ediff-even-diff-A ((t (:inherit ediff-odd-diff-A))))
 '(ediff-even-diff-B ((t (:inherit ediff-odd-diff-B))))
 '(ediff-even-diff-C ((t (:inherit ediff-odd-diff-C))))
 '(org-date ((t (:background "#3F51B5" :foreground "#FAFAFA"))))
 '(vr/match-separator-face ((t (:foreground "#FAFAFA" :weight ultra-bold))))
 '(vr/match-0 ((t (:background "#7E57C2"))))
 '(vr/match-1 ((t (:background "#5C6BC0"))))
 '(vr/group-0 ((t (:background "#26A69A"))))
 '(vr/group-1 ((t (:background "#66BB6A"))))
 '(vr/group-2 ((t (:background "#D4E157"))))
 '(num3-face-even ((t (:underline t))))
 '(num3-face-odd ((t nil)))
 '(magit-branch-current ((t (:inherit magit-branch-local :foreground "#42A5F5" :weight bold))))
 '(vertical-border ((t (:inherit default :inverse-video t))))
 '(helm-non-file-buffer ((t (:inherit italic :weight light))))
 '(org-priority-low ((t (:inherit info))))
 '(org-priority-medium ((t (:inherit warning))))
 '(org-priority-high ((t (:inherit error))))
 '(org-link ((t (:inherit link))))
 '(org-agenda-clocking ((t (:weight ultra-bold :background "gray20" :inherit default))))
 '(line-number ((t (:inherit default :foreground "gray30"))))
 '(line-number-current-line ((t (:inherit line-number :foreground "grey70"))))
 '(org-ellipsis ((t nil)))
 '(cov-coverage-run-face ((t (:inherit info))))
 '(cov-coverage-not-run-face ((t (:inherit error))))
 '(rainbow-delimiters-base-face ((default (:inherit nil))))
 '(rainbow-delimiters-unmatched-face ((t (:inherit (error rainbow-delimiters-base-face) :inverse-video t))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit rainbow-delimiters-unmatched-face))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#EC407A" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#7E57C2"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "#42A5F5"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#26C6DA" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#26A69A"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#66BB6A"))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "#FFEE58"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#FFA726" :inherit rainbow-delimiters-base-face))))
 '(magit-branch-local ((t (:foreground "#4FC3F7"))))
 '(magit-branch-remote ((t (:foreground "#9CCC65"))))
 '(magit-branch-remote-head ((t (:inherit magit-branch-remote :foreground "#26A69A"))))
 '(magit-branch-upstream ((t (:slant italic))))
 '(dashboard-heading ((t (:inherit helm-source-header))))
 '(default ((t (:inherit nil :stipple nil :background "gray5" :foreground "white smoke" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight semi-bold :height 120 :width normal :foundry "ADBO" :family "Source Code Pro")))))

(provide-theme 'cpp-entwickler.de)
